### ISSUE TITLE
mediapipe, import error :DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by aditya54321** [ntu-rris/google-mediapipe#4]
**This is happening while import the mediapipe module.**
**
 import mediapipe
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    import mediapipe
  File "C:\Users\new user\AppData\Local\Programs\Python\Python37\lib\site-packages\mediapipe\__init__.py", line 16, in <module>
    from mediapipe.python import *
  File "C:\Users\new user\AppData\Local\Programs\Python\Python37\lib\site-packages\mediapipe\python\__init__.py", line 17, in <module>
    from mediapipe.python._framework_bindings import resource_util
ImportError: DLL load failed: The specified module could not be found.               

**
How to solve this problem
![mediapipe](https://user-images.githubusercontent.com/63996946/133121292-b3d4e0fa-8d9a-4e5f-8d3a-f2c576eafb95.png)

**Comment by guanming001** [comment]
@aditya54321 you may want to direct this issue to [google/mediapipe](https://github.com/google/mediapipe) as this repo only contains demo applications.

Anyway not sure if this is related to [issue](https://github.com/google/mediapipe/issues/1839#issuecomment-817363779)
